chrome.runtime.onMessage.addListener(function(response, sender, sendResponse) {

	// prompt("Copy to clipboard: Ctrl+C, Enter", response);
	// ************** ORDER ID & ENTERPRISE ID PASSED TO URL: **************
	window.open("http://kibana.int.cj.com/#/dashboard/CIE_MATT_MARA__dkcie?_g=(refreshInterval:(display:Off,pause:!f,section:0,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(filters:!((meta:(disabled:!f,index:%5Bactivity-%5DYYYY-MM-DD,key:coreview.query.coupon,negate:!t,value:null),query:(match:(coreview.query.coupon:(query:null,type:phrase)))),(meta:(disabled:!f,index:%5Bactivity-%5DYYYY-MM-DD,key:coreview.enterprise_id,negate:!t,value:'1'),query:(match:(coreview.enterprise_id:(query:'1',type:phrase)))),(meta:(disabled:!f,index:%5Bactivity-%5DYYYY-MM-DD,key:coreview.enterprise_id,negate:!f,value:'"+response[0]+"'),query:(match:(coreview.enterprise_id:(query:'"+response[0]+"',type:phrase))))),panels:!((col:1,columns:!(coreview.event_time_utc,coreview.last_click_time,coreview.query.oid,coreview.request_url,coreview.query_string,coreview.referring_url,coreview.client_ip_address),id:dkcieSrch,row:8,size_x:12,size_y:4,sort:!(coreview.event_time_utc,desc),type:search),(col:8,id:VIEWS__dkcie,row:1,size_x:5,size_y:3,type:visualization),(col:8,id:VIEWS_IN_AP__dkcie,row:4,size_x:5,size_y:3,type:visualization),(col:1,id:HITS__dkcie,row:1,size_x:4,size_y:2,type:visualization),(col:1,id:DK4_01-apbad_error_code,row:3,size_x:4,size_y:2,type:visualization),(col:5,id:DK_01-ENTERPRISE_ID,row:1,size_x:3,size_y:4,type:visualization),(col:1,id:DK4_coupon-code,row:5,size_x:7,size_y:3,type:visualization)),query:(query_string:(analyze_wildcard:!t,query:'NOT%20coreview.user_agent:%20%22Master%20TMS%20bot%22%20AND%20coreview.query.oid:%20%22"+response[1]+"%22')),title:CIE_MATT_MARA__dkcie)");
	// ************** Enterprise ID ONLY ******************
	// window.open("http://kibana.int.cj.com/#/dashboard/CIE_MATT_MARA__dkcie?_g=(refreshInterval:(display:Off,pause:!f,section:0,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(filters:!((meta:(disabled:!f,index:%5Bactivity-%5DYYYY-MM-DD,key:coreview.query.coupon,negate:!t,value:null),query:(match:(coreview.query.coupon:(query:null,type:phrase)))),(meta:(disabled:!f,index:%5Bactivity-%5DYYYY-MM-DD,key:coreview.enterprise_id,negate:!t,value:'1'),query:(match:(coreview.enterprise_id:(query:'1',type:phrase)))),(meta:(disabled:!f,index:%5Bactivity-%5DYYYY-MM-DD,key:coreview.enterprise_id,negate:!f,value:"+response[0]+"),query:(match:(coreview.enterprise_id:(query:'"+response[0]+"',type:phrase))))),panels:!((col:1,columns:!(coreview.event_time_utc,coreview.last_click_time,coreview.query.oid,coreview.request_url,coreview.query_string,coreview.referring_url,coreview.client_ip_address),id:dkcieSrch,row:8,size_x:12,size_y:4,sort:!(coreview.event_time_utc,desc),type:search),(col:8,id:VIEWS__dkcie,row:1,size_x:5,size_y:3,type:visualization),(col:8,id:VIEWS_IN_AP__dkcie,row:4,size_x:5,size_y:3,type:visualization),(col:1,id:HITS__dkcie,row:1,size_x:4,size_y:2,type:visualization),(col:1,id:DK4_01-apbad_error_code,row:3,size_x:4,size_y:2,type:visualization),(col:5,id:DK_01-ENTERPRISE_ID,row:1,size_x:3,size_y:4,type:visualization),(col:1,id:DK4_coupon-code,row:5,size_x:7,size_y:3,type:visualization)),query:(query_string:(analyze_wildcard:!t,query:'NOT%20coreview.user_agent:%20%22Master%20TMS%20bot%22')),title:CIE_MATT_MARA__dkcie)")
});

